### ISSUE TITLE
StrictDeepOmit

### ISSUE THREAD

**Issue by xenoterracide** [ts-essentials/ts-essentials#340]
Would it be possible to have a `StrictDeepOmit` that wouldn't allow you to specify keys that don't exist.

**Comment by Beraliv** [comment]
Hey!

Could you please specify the case when you can reproduce it?

It would be great if you attach [TypeScript Playground](https://www.typescriptlang.org/play) where you can reproduce the problem

Because currently `DeepOmit` has the generic type `Filter` that does it. If it's not working in the specific case, that would be easier to fix

**Comment by Beraliv** [comment]
@xenoterracide I will close this one as stale
