### ISSUE TITLE
Bug: XOR may not be compatible with Omit

### ISSUE THREAD

**Issue by arnard76** [ts-essentials/ts-essentials#420]
### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript`                           | `5.3.3` |
| `ts-essentials`                        | `9.4.0` |

### Repro Code

```typescript
/** Existing types from ts-essential */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = T | U extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;

// Types to highlight issue
type BaseBus = {
  wheels: number;
  capacity: number;
  id: string;
}

type PublicBus = BaseBus & {
  town: string;
}

type SchoolBus = BaseBus & {
  school: string;
  driver: string;
}

type Bus = XOR<PublicBus, SchoolBus>;

type BusWithLicensePlate = Omit<Bus, 'id'> & { licensePlate: string }

function checkBusType(bus: BusWithLicensePlate){
  if(bus.school){
    // bus should recognised as type SchoolBus
    bus.town // and this should throw error 🥲
    bus.driver // and this should `driver: string` instead of `driver?: string | undefined`
  }
}
```

### TypeScript Playground

https://www.typescriptlang.org/play/?#code/FAegVGAECiAeCWBnALvAdgc0sgngBwFNFIAzAJwHsBbbRAWiMQLVQEMAbSMEYXQyAOrxkACwoBXZAB4AKgBpIAVQB8kALyQA3pADaABUjoYsAMbtxAEwJSA1gRwUSkeZDsOnKgLoB+AFyQ0AgA3AjJIAF8Abl58AkgADQB5ACVZBRV1Z0gAHyVIAlhkZgtiCgAjACsCE2RIb0gACiFRCWkXDIAyJQBKHMbmsUkpRQUZVS6ZXv8ZPsVo0BBnWOJkCkgReAwRdk2RWqREcQIY-gAhViZT8WINTWBISAB3EQICdkR-NHEqMtDoh5MrDwrBMwhwn2+vzI-0MFn8KDI6Aw0XCwBOcT04jKOxMVxukHOl2ukC6dweq0eaHhyERmBRaL4cQAyiYxBR2HjMoSCJzSfdIIhWRR2dTacj+RZESEyKKkfT0QTiRokqlMdj4LjrgoWWyOddlPNGYrEAMADIa5hMPTsVhFTKJKjCKR4hQAcngFld4y0kBxloI1ttBFlmAiaJI4jQNXgFDQkFZ1RseJksQaZWu-jxZotaCtNqK3TJhhIaeuADpBbrC-yHiBFuniIhBuwLJAyNUKBg0EgCK2LthYpAdcK9Yga5AG2WKXG65BWGhW6IkALm4uRJRHvkyJQwoA+DcATrvjyeS+DSyCz+dr5dNiQtyAAAxP0pDGHvhlzRVYrccD6foT8Ao0kifSRlYJDoL2978qi4RAA

### Expected Result

```
if(bus.school){
    // bus should recognised as type SchoolBus
    bus.town // and this should throw error 🥲
    bus.driver // and this should `driver: string`
  }
```

### Actual Result

```
if(bus.school){
    // bus is not recognised as type SchoolBus
    bus.town // and this is allowed and has type of 'town?: string | undefined'
    bus.driver // and this has a type of 'driver?: string | undefined' when in fact it is always a string
  }
```

Has anyone else ran into this issue before? Let me know if this is just a "me" problem 😅😅. This could also be considered an enhancement to the XOR type rather than a bug.

**Comment by som-sm** [comment]
@arnard76 The problem lies with how `BusWithLicensePlate` type is being constructed. The `Omit` utility type is actually **NOT** a homomorphic type, so it doesn't work as expected with union types.

So, `BusWithLicensePlate` type is **NOT** actually the following:
```ts
type BusWithLicensePlate =
  | (Omit<PublicBus, "id"> & { licensePlate: string })
  | (Omit<SchoolBus, "id"> & { licensePlate: string });
```

Instead it's the following type:
```ts
type BusWithLicensePlate = {
    wheels: number;
    capacity: number;
    school?: string | undefined;
    driver?: string | undefined;
    town?: string | undefined;
    licensePlate: string;
}
```
This happens because `Omit` processes the union as a whole rather than distributing over each member of the union.

To address this, instead of using `Omit`, you can either use `StrictOmit` from `ts-essentials` or you can define your own version of `Omit` that works well with unions, like the following:

```ts
type BetterOmit<T, K> = {
  [P in keyof T as Exclude<P, K>]: T[P]; }
}
```

<br />

Now, when you narrow `bus` using the check, `if (bus.school)`:
- `bus.driver` would correctly narrow down to be of type `string`
-  However, `bus.town` would not throw an error because that's not how `XOR` is designed. If you notice the type of `BusWithLicensePlate`:

    ```ts
    type BusWithLicensePlate = {
        wheels: number;
        capacity: number;
        school?: never;
        driver?: never;
        town: string;
        licensePlate: string;
    } | {
        wheels: number;
        capacity: number;
        school: string;
        driver: string;
        town?: never;
        licensePlate: string;
    }
    ```
    Notice that both the union members have all the keys, and:
    - The first member has `school` and `driver` keys as `?: never` (although the tooltip shows `?: undefined`, which is technically the same thing) 
    - and the second member has `town` as `?: never`.
    
    Therefore, even if you narrow down to the second member, you'd still be able to access `town`, it's just that it's type would be `undefined`.

Link to [playground](https://tsplay.dev/mpM4pW).

Hope that made some sense, @Beraliv might have more to add.

**Comment by som-sm** [comment]
Also, it's better to replace the check `if (bus.school)` with `if (typeof bus.school === "string")`, because the former misses the case where `bus.school` is an empty string. So, with the former check, the `else` branch would **NOT** be narrowed correctly.

- `else` is **NOT** narrowed correctly with `if (bus.school)` check

    <img width="1384" alt="image" src="https://github.com/user-attachments/assets/9cb4f74c-b478-4723-96ef-670256be4e53">
    
- `else` is narrowed correctly with `if (typeof bus.school === "string")`

   <img width="1345" alt="image" src="https://github.com/user-attachments/assets/2379218d-4da6-4d09-975f-03efe20d04b7">

**Comment by arnard76** [comment]
Thank you for your reply @som-sm, I understand the issue now. This is not a bug with XOR and I will try the upgraded Omit  instead. 

Also, I appreciate your note at the end because I didn't notice that mistake 💯💯🙃🙃

**Comment by som-sm** [comment]
@arnard76 If you really want `bus.town` to error out, you can consider switching to a [discriminated union](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) instead of XOR.

You can refer to [this playground](https://tsplay.dev/wXx5Ow).

**Comment by arnard76** [comment]
Oh cool, I didn't know unions could be used like that. Thanks!Is the idea to use XOR when there is no discriminate property?
-------- Original message --------From: Som Shekhar Mukherjee ***@***.***> Date: 18/11/2024  22:00  (GMT+12:00) To: ts-essentials/ts-essentials ***@***.***> Cc: Arnav ***@***.***>, Mention ***@***.***> Subject: Re: [ts-essentials/ts-essentials] Bug: XOR may not be compatible with Omit (Issue #420) 
@arnard76 If you really want bus.town to error out, you can consider switching to a discriminated union instead of XOR.
You can refer to this playground.

**Comment by som-sm** [comment]
Yup, `XOR` is helpful in situations where you either can’t or don’t want to add a discriminant property.

**Comment by arnard76** [comment]
Ok cool, that makes sense
-------- Original message --------From: Som Shekhar Mukherjee ***@***.***> Date: 18/11/2024  22:14  (GMT+12:00) To: ts-essentials/ts-essentials ***@***.***> Cc: Arnav ***@***.***>, Mention ***@***.***> Subject: Re: [ts-essentials/ts-essentials] Bug: XOR may not be compatible with Omit (Issue #420) 
Yup, XOR is helpful in situations where you either can’t or don’t want to add a discriminant property.
