### ISSUE TITLE
Allowing a deeply nested type to have additional properties, but maintain strictness of base type

### ISSUE THREAD

**Issue by duro** [ts-essentials/ts-essentials#97]
Sorry if this is a poor place to leave this question, but I am lost trying to find answer anywhere, and you guys know your type-fu.

I'm trying to create a utility type which takes in a deeply nested interface, and respects said strictness of the types defined in that interface, but for any property which is an object (including the root object, allows additional keys to be present and essentially be typed like a `Record<any, unknown>`

For example, here is in input interface:

```
interface ITestType {
  userId: string
  anonymousId: string,
  attributes: {
    color: string,
    size: {
      width: number,
      height: number
    }
  }
  properties: {
    [key: string]: unknown
  }
  timestamp: Date
}
```

And I could love to redefine this using some kind of utility type like so:

```
type NewType = DeepAllowNonDefinedKeys<ITestType>
```

Where `DeepAllowNonDefinedKeys` would allow the the following shape to be permitted:

```
{
  additionalField1: 'ssjhshs',
  userId: 'jdjdj',
  anonymousId: 'dhjdhd',
  attributes: {
    additionalField2: 'ssjhshs',
    color: 'blue',
    size: {
      width: 123,
      height: 456,
      isGiant: true
    }
  },
  properties: { fake: true },
  timestamp: new Date()
}
```

The reason I need this is for use with a library I use for validating objects as the exit and enter two services (I am currently using io-ts for this), but I have seen other libraries work similarly.

What io-ts does is it will permit an input object which has additional keys, but will only validate they keys which have been defined.

Any guidance you fine TypeScript wizards could provide would be greatly appreciated.

I had a first pass at this sort of working with the below, but it started to fall apart when I threw things like rested `Record<any, unknown>` types into the nested interface:

```
export type Primitive = string | number | boolean | bigint | symbol | undefined | null

export type AllowAdditionalProps<T> = T & { [key: string]: any }

export type DeepAllowAdditionalProps<T> = T extends Primitive
  ? T
  : T extends {}
  ? AllowAdditionalProps<T> &
      {
        [K in keyof T]: T[K] extends Primitive
          ? T[K]
          : AllowAdditionalProps<T[K]> & DeepAllowAdditionalProps<T[K]>
      }
  : AllowAdditionalProps<T>
```

**Comment by quezak** [comment]
The best place for such a question would be, obviously, Stack Overflow :)

If you're interested in validating (or rejecting) additional properties, [class-validator](https://github.com/typestack/class-validator) + [class-transformer](https://github.com/typestack/class-transformer) may have some tricks.

If you're interested in only passing such an object to a function, it's easily solved with a generic argument, thanks to Typescript's structural type system:
```
function testFn<T extends ITestType>(t: T): void { }

testFn({
    additionalField1: 'ssjhshs',
    userId: 'jdjdj',
    anonymousId: 'dhjdhd',
    attributes: {
        additionalField2: 'ssjhshs',
        color: 'blue',
        size: {
            width: 123,
            height: 456,
            isGiant: true,
        },
    },
    properties: { fake: true },
    timestamp: new Date(),
});
```

Maybe a similar trick can be used to write an explicit type `DeepExtended<T>` or something?

Since this also looks kinda like a feature request, I'll leave the issue open for now, maybe someone will have an idea.
But we'll need more confirmation that such a type would be useful if we wanted to include it in ts-essentials.

**Comment by Beraliv** [comment]
It looks like this issue is stale and no one is interested in it so I can close it. If anyone believes this feature will be helpful, I can reopen it
